-- Run in Supabase: SQL Editor -> New query -> Run
-- Creates diseases table and seeds 120+ conditions

CREATE TABLE IF NOT EXISTS public.diseases (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    category TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS diseases_name_lower_idx ON public.diseases (LOWER(name));

INSERT INTO public.diseases (name, category) VALUES
    ('Acne', NULL),
    ('Acute bronchitis', NULL),
    ('Alcohol use disorder', NULL),
    ('Allergic rhinitis', NULL),
    ('Alzheimer disease', NULL),
    ('Anemia', NULL),
    ('Anxiety disorder', 'Mental health'),
    ('Asthma', 'Respiratory'),
    ('Atrial fibrillation', NULL),
    ('Attention deficit hyperactivity disorder', NULL),
    ('Autism spectrum disorder', NULL),
    ('Back pain', NULL),
    ('Bipolar disorder', NULL),
    ('Bladder cancer', NULL),
    ('Breast cancer', NULL),
    ('Bronchitis', NULL),
    ('Carpal tunnel syndrome', NULL),
    ('Cataracts', NULL),
    ('Celiac disease', NULL),
    ('Cervical cancer', NULL),
    ('Chronic fatigue syndrome', NULL),
    ('Chronic kidney disease', NULL),
    ('Chronic obstructive pulmonary disease', 'Respiratory'),
    ('Chronic pain', NULL),
    ('Colorectal cancer', NULL),
    ('Congestive heart failure', NULL),
    ('Coronary artery disease', 'Cardiovascular'),
    ('Crohn disease', NULL),
    ('Depression', 'Mental health'),
    ('Dermatitis', NULL),
    ('Diabetes insipidus', NULL),
    ('Diabetes type 1', 'Endocrine'),
    ('Diabetes type 2', 'Endocrine'),
    ('Diverticulitis', NULL),
    ('Eating disorder', NULL),
    ('Eczema', NULL),
    ('Emphysema', NULL),
    ('Endometriosis', NULL),
    ('Epilepsy', NULL),
    ('Erectile dysfunction', NULL),
    ('Fibromyalgia', NULL),
    ('Gallstones', NULL),
    ('Gastroesophageal reflux disease', NULL),
    ('Generalized anxiety disorder', NULL),
    ('Glaucoma', NULL),
    ('Gout', NULL),
    ('Graves disease', NULL),
    ('Hashimoto thyroiditis', NULL),
    ('Heart failure', NULL),
    ('Hemophilia', NULL),
    ('Hepatitis B', NULL),
    ('Hepatitis C', NULL),
    ('Herniated disc', NULL),
    ('High blood pressure', 'Cardiovascular'),
    ('High cholesterol', NULL),
    ('HIV/AIDS', NULL),
    ('Hodgkin lymphoma', NULL),
    ('Huntington disease', NULL),
    ('Hyperthyroidism', NULL),
    ('Hypothyroidism', NULL),
    ('Inflammatory bowel disease', NULL),
    ('Insomnia', NULL),
    ('Interstitial cystitis', NULL),
    ('Irritable bowel syndrome', NULL),
    ('Kidney stones', NULL),
    ('Lactose intolerance', NULL),
    ('Liver cirrhosis', NULL),
    ('Lung cancer', NULL),
    ('Lupus', NULL),
    ('Lyme disease', NULL),
    ('Macular degeneration', NULL),
    ('Major depressive disorder', NULL),
    ('Melanoma', NULL),
    ('Migraine', NULL),
    ('Multiple sclerosis', NULL),
    ('Myasthenia gravis', NULL),
    ('Obesity', NULL),
    ('Obsessive compulsive disorder', NULL),
    ('Osteoarthritis', 'Musculoskeletal'),
    ('Osteoporosis', NULL),
    ('Ovarian cancer', NULL),
    ('Pacemaker', NULL),
    ('Pancreatitis', NULL),
    ('Parkinson disease', NULL),
    ('Peptic ulcer disease', NULL),
    ('Peripheral artery disease', NULL),
    ('Polycystic ovary syndrome', NULL),
    ('Post traumatic stress disorder', NULL),
    ('Prediabetes', NULL),
    ('Prostate cancer', NULL),
    ('Psoriasis', NULL),
    ('Psoriatic arthritis', NULL),
    ('Pulmonary embolism', NULL),
    ('Restless legs syndrome', NULL),
    ('Rheumatoid arthritis', 'Musculoskeletal'),
    ('Rosacea', NULL),
    ('Schizophrenia', NULL),
    ('Sciatica', NULL),
    ('Seasonal affective disorder', NULL),
    ('Seizure disorder', NULL),
    ('Sickle cell disease', NULL),
    ('Sinusitis', NULL),
    ('Sleep apnea', NULL),
    ('Spinal stenosis', NULL),
    ('Stroke history', NULL),
    ('Substance use disorder', NULL),
    ('Systemic lupus erythematosus', NULL),
    ('Tension headache', NULL),
    ('Thalassemia', NULL),
    ('Thyroid cancer', NULL),
    ('Tourette syndrome', NULL),
    ('Tuberculosis', NULL),
    ('Ulcerative colitis', NULL),
    ('Urinary incontinence', NULL),
    ('Urinary tract infection recurrent', NULL),
    ('Uterine fibroids', NULL),
    ('Varicose veins', NULL),
    ('Vitiligo', NULL),
    ('Vitamin D deficiency', NULL),
    ('Von Willebrand disease', NULL)
ON CONFLICT (name) DO NOTHING;

-- Backend uses direct Postgres (pooler); disable RLS for server-side access
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.diseases DISABLE ROW LEVEL SECURITY;